# Generated by Django 4.1.5 on 2023-03-03 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("phoneNumber", models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=750)),
                ("labs", models.ManyToManyField(to="app.lab")),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phoneNumber", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Man", "Man"), ("Women", "Women")],
                        default=0,
                        max_length=5,
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=750)),
                ("score", models.CharField(max_length=100)),
                (
                    "medicalAnalysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.medicalanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phoneNumber", models.CharField(blank=True, max_length=11, null=True)),
                ("salary", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "adminCreateBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.lab",
                    ),
                ),
            ],
        ),
    ]
