# Generated by Django 4.1.5 on 2023-03-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="lab",
            name="phoneNumber",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
