# Generated by Django 4.1.5 on 2023-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_lab_address_alter_lab_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalanalysis",
            name="price",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="medicalAnalysis",
            field=models.ManyToManyField(to="app.medicalanalysis"),
        ),
    ]
