# Generated by Django 4.1.5 on 2023-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_medicalanalysis_price_patient_medicalanalysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalanalysis",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
