# Generated by Django 4.1.5 on 2023-03-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_medicalanalysis_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalanalysis",
            name="labs",
        ),
    ]
