# Generated by Django 4.1.5 on 2023-03-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="patientDoctorName",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
