# Generated by Django 4.1.5 on 2023-03-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_patient_description_patient_patientdoctorname"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
