# Generated by Django 4.1.5 on 2023-03-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_patient_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="medicalAnalysis",
        ),
        migrations.RemoveField(
            model_name="result",
            name="medicalAnalysis",
        ),
        migrations.RemoveField(
            model_name="score",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="score",
            name="result",
        ),
        migrations.DeleteModel(
            name="MedicalAnalysis",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
        migrations.DeleteModel(
            name="Result",
        ),
        migrations.DeleteModel(
            name="Score",
        ),
    ]
