# Generated by Django 4.1.5 on 2023-03-04 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab", "0001_initial"),
        ("app", "0010_remove_patient_medicalanalysis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phoneNumber", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Man", "Man"), ("Women", "Women")],
                        default=0,
                        max_length=5,
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "patientDoctorName",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("done", models.BooleanField(default=False)),
                ("dateTime", models.DateTimeField(auto_now_add=True, null=True)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.lab",
                    ),
                ),
                ("medicalAnalysis", models.ManyToManyField(to="lab.medicalanalysis")),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.CharField(max_length=100)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lab.result"
                    ),
                ),
            ],
        ),
    ]
