# Generated by Django 4.1.5 on 2023-03-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_doctor_alter_patient_patientdoctorname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patientDoctorName",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
