# Generated by Django 4.1.5 on 2023-03-05 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_alter_patient_patientdoctorname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patientDoctorName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.doctor",
            ),
        ),
    ]
