# Generated by Django 4.1.5 on 2023-03-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0004_alter_patient_patientdoctorname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="dateTime",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
